server 
{
    listen 3000;
    # The directory where you copied your static files in the Dockerfile
    root /var/www/html;
    index index.html;

    location / 
    {
        # This helps handle internal routing and returns 404 if a file isn't found
        try_files $uri $uri/ =404;
    }
}
