# By default Redis only accepts connections from 127.0.0.1 (localhost)
# We change this to 0.0.0.0 so OTHER containers can connect to it
bind 0.0.0.0

# Default port
port 6379

# Don't run as a background daemon (Docker needs the process in foreground)
daemonize no

# How much RAM Redis can use for cache
# If it exceeds this, it will start evicting old entries
maxmemory 256mb

# Eviction policy: when RAM is full, delete the LEAST RECENTLY USED keys
# This is the most sensible policy for a WordPress cache
maxmemory-policy allkeys-lru

# Disable saving to disk (we want pure in-memory cache, no persistence needed)
save ""

#Disable protected mode
protected-mode no